import { TypeOrmModuleOptions } from '@nestjs/typeorm';
import * as dotenv from 'dotenv';
import {
  Usuario,
  Producto,
  Cliente,
  PrecioCliente,
  Trabajador,
  LaborTipo,
  LaborTarifa,
  Pedido,
  DetallePedido,
  Ruta,
  ItemRuta,
  IntentoEntrega,
  LiquidacionRuta,
  Venta,
  DetalleVenta,
  Pago,
  Cartera,
  MovimientoCaja,
  CierreCaja,
  InventarioInicial,
  MovimientoInventario,
  CierreInventario,
  ProduccionDiaria,
  AperturaDiaria,
  CierreDiario,
  TrabajadorLabor,
  PagoTrabajador,
  AnticipoPrestamo,
  AbonoDeuda,
  CambioAuditoria,
  LogActividad,
  ConfiguracionEmpresa,
} from './entities';

dotenv.config({ path: '.env.local' });
dotenv.config({ path: '.env' });

export const typeOrmConfig: TypeOrmModuleOptions = {
  type: 'mysql',
  host: process.env.DB_HOST || process.env.MYSQLHOST || 'localhost',
  port: parseInt(process.env.DB_PORT || process.env.MYSQLPORT || '3306', 10),
  username: process.env.DB_USERNAME || process.env.MYSQLUSER || 'root',
  password: process.env.DB_PASSWORD || process.env.MYSQLPASSWORD || 'root',
  database: process.env.MYSQL_DATABASE || 'hotel',
  entities: [
    Usuario,
    Producto,
    Cliente,
    PrecioCliente,
    Trabajador,
    LaborTipo,
    LaborTarifa,
    Pedido,
    DetallePedido,
    Ruta,
    ItemRuta,
    IntentoEntrega,
    LiquidacionRuta,
    Venta,
    DetalleVenta,
    Pago,
    Cartera,
    MovimientoCaja,
    CierreCaja,
    InventarioInicial,
    MovimientoInventario,
    CierreInventario,
    ProduccionDiaria,
    AperturaDiaria,
    CierreDiario,
    TrabajadorLabor,
    PagoTrabajador,
    AnticipoPrestamo,
    AbonoDeuda,
    CambioAuditoria,
    LogActividad,
    ConfiguracionEmpresa,
  ],
  synchronize: process.env.DB_SYNCHRONIZE === 'true',
  logging: process.env.NODE_ENV === 'development',
  dropSchema: false,
};
